base_url = "https://p-rallapally.github.io/"
title = "Pratyush Rallapally"
description = "Personal site"
compile_sass = false
generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
    { name = "tags" },
]

[markdown]
render_emoji = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
author = "p-rallapally"